name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build Image to Registry
        run: gcloud builds submit --tag europe-west3-docker.pkg.dev/bamboo-antler-491206-h0/notely-ar-repo/notely:latest .

      - name: Run migration
        run: npm run db:migrate

      - name: Deploy Container to Cloud Run
        run: gcloud run deploy notely --image europe-west3-docker.pkg.dev/bamboo-antler-491206-h0/notely-ar-repo/notely:latest --region europe-west1 --allow-unauthenticated --project bamboo-antler-491206-h0 --max-instances=4
